services:
  code-server:
    image: code-server:latest
    environment:
      - PASSWORD=changeme
      - HTTPS=true
      #- HOST=myhost.exanple.com
      #- CERT=/certs/server.crt
      #- CERTKEY=/certs/server.key
      #- PORT=8443
      #- INSECURE=false
    ports:
      - "8443:8443"
    volumes:
      - code-server:/home/nix
    restart: unless-stopped

volumes:
  code-server:
